### ISSUE TITLE
Can you add some tests for it?

### ISSUE THREAD

**Issue by thiagolunardi** [fel1xw/react-robohash#1]
It would be nice to know that the component is actually tested. Especially for those planning to consume it in real production projects.

**Comment by fel1xw** [comment]
@thiagolunardi I can add some tests verifying that the url includes specific properties or not. :)

**Comment by thiagolunardi** [comment]
Meh, I'm expecting about the what's going to be rendered by the component itself.

**Comment by fel1xw** [comment]
tests are added now for the logic part..
